version: '3.8'

services:
  oracledb:
    image:  container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_PWD=welcome1
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/startup
